apiVersion: kueue.x-k8s.io/v1beta1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/name: admission-controller
    app.kubernetes.io/managed-by: kustomize
  name: workload-sample
spec:
  # TODO(user): Add fields here
